spring:
  # thymeleaf
  thymeleaf:
    # \u5173\u95ED\u7F13\u5B58
    cache: false
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.gongyanhui.top:3306/seckill
    username: root
    password: 123456
    hikari:
      # \u8FDE\u63A5\u6C60\u540D
      pool-name: DateHikariCP
      # \u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: 5
      # \u7A7A\u95F2\u8FDE\u63A5\u5B58\u6D3B\u6700\u5927\u65F6\u95F4\uFF0C\u9ED8\u8BA4600000(10\u5206\u949F)
      idle-timeout: 1800000
      # \u6700\u5927\u8FDE\u63A5\u6570 \u9ED8\u8BA410
      maximum-pool-size: 10
      # \u4ECE\u8FDE\u63A5\u6C60\u8FD4\u56DE\u7684\u8FDE\u63A5\u81EA\u52A8\u63D0\u4EA4
      auto-commit: true
      # \u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4 0\u8868\u793A\u6C38\u4E45\u5B58\u6D3B \u9ED8\u8BA41800000(30\u5206\u949F)
      max-lifetime: 1800000
      # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4 \u9ED8\u8BA430000(30s)
      connection-timeout: 30000
      # \u5FC3\u8DF3\u673A\u5236 \u6D4B\u8BD5\u8FDE\u63A5\u662F\u5426\u53EF\u7528\u7684\u67E5\u8BE2\u8BED\u53E5
      connection-test-query: SELECT 1

  redis:
    host: www.gongyanhui.top
    # 数据库哪个库 默认0
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间 默认-1
        max-wait: 10000ms
        # 最小空闲连接 默认0
        max-idle: 200

# Mybatis-plus\u914D\u7F6E
mybatis-plus:
  # \u914D\u7F6EMapper.xml\u6620\u5C04\u6587\u4EF6
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # \u914D\u7F6EMybatis\u6570\u636E\u8FD4\u56DE\u7C7B\u578B\u522B\u540D(\u9ED8\u8BA4\u522B\u540D\u662F\u7C7B\u540D)
  type-aliases-package: com.gongyanhui.seckill.pojo

# Mybatis SQL\u6253\u5370(\u65B9\u6CD5\u63A5\u53E3\u6240\u5728\u7684\u5305\uFF0C\u4E0D\u662FMapper.xml\u6240\u5728\u7684\u5305)
logging:
  level:
    com.gongyanhui.seckill.mapper: debug